name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install node modules
        run: npm i 
        working-directory: ./project/leogreen_server/

      - name: Build Angular project and zip it
        run: |
          npm run build:prod
          tar -czf leoGreen.tgz dist/leoGreen
        working-directory: ./project/client/leoGreen/

      - name: install ssh key
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER_IP }}
          alias: server

      - name: copy built files to server
        run: |
          scp *.tgz server:
        working-directory: ./project/client/leoGreen/
